const CONFIG = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL!,
  API_KEY: process.env.NEXT_PUBLIC_API_KEY!,
  REQUEST_ENDPOINT: process.env.NEXT_PUBLIC_REQUEST_ENDPOINT as string,
  STRIPE_PUBLISHABLE_KEY: process.env
    .NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY as string
};

export default CONFIG;
